preset: recommended

finder:
    exclude:
        - "vendor"

enabled:
    - phpdoc_link_to_see
    - phpdoc_return_self_reference
    - phpdoc_no_empty_return
    - return_type_declaration
    - const_visibility_required
    - not_operator_with_successor_space
    - concat_with_spaces

disabled:
    - concat_without_spaces
