preset: recommended

finder:
    exclude:
        - "vendor"

enabled:
    - blank_line_before_break
    - blank_line_before_continue
    - blank_line_before_declare
    - phpdoc_link_to_see
    - phpdoc_return_self_reference
    - phpdoc_no_empty_return
    - const_visibility_required
    - not_operator_with_successor_space
    - concat_with_spaces
    - no_extra_block_blank_lines
    - property_separation
    - standardize_increment
    - php_unit_ordered_covers
    - php_unit_set_up_tear_down_visibility

disabled:
    - concat_without_spaces
    - self_accessor
