preset: recommended

finder:
    exclude:
        - "vendor"

enabled:
    - phpdoc_link_to_see
    - phpdoc_return_self_reference
    - short_scalar_cast
    - return_type_declaration
    - concat_with_spaces
