preset: recommended

finder:
    exclude:
        - "vendor"

enabled:
    - phpdoc_link_to_see
    - phpdoc_return_self_reference
    - return_type_declaration
    - concat_with_spaces
    - const_separation
    - const_visibility_required

disabled:
    - concat_without_spaces
