<?php

declare(strict_types=1);

// TODO : regarder ici : https://github.com/zendframework/zend-expressive-router/blob/master/src/Middleware/DispatchMiddleware.php

// TODO : regarder ici https://github.com/zrecore/Spark/blob/master/src/Handler/RouteHandler.php    et https://github.com/equip/framework/blob/master/src/Handler/DispatchHandler.php

namespace Chiron\Middleware;

use Chiron\Routing\RouteResult;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\MiddlewareInterface;
use Psr\Http\Server\RequestHandlerInterface;

class DispatcherMiddleware implements MiddlewareInterface
{
    /**
     * Process a server request and return a response.
     */
    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {
        $routeResult = $request->getAttribute(RouteResult::class, false);

        // if the route is not a failure, return the response generated by the route handler.
        if ($routeResult && ! $routeResult->isFailure()) {
            return $routeResult->getMatchedRoute()->handle($request);
        }

        // TODO : ajouter le template 404 not found comme requestHandler par défault, car pour le moment on retourne uniquement une Response vide.
        return $handler->handle($request);
    }
}
